name: Go

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:
    name: Deploy API
    runs-on: ubuntu-latest
    steps:

    - name: Push to heroku repo
      env:
        HEROKU_API_TOKEN: ${{ secrets.HEROKU_API_TOKEN }}
        HEROKU_APP_NAME: covidscript
      if: github.ref == 'refs/heads/master'
      run: git push https://heroku:$HEROKU_API_TOKEN@git.heroku.com/covidscript.git origin/master:master
